export interface Poligono {
  ciudad: string;
  descripcion: string;
  clasificacionId: number;
}

export const LISTA_POLIGONOS: Poligono[] = [
  { ciudad: "Acapulco.", descripcion: "Acapulco Norte.", clasificacionId: 3 },
  { ciudad: "Acapulco.", descripcion: "Acapulco Sur.", clasificacionId: 3 },
  { ciudad: "Aguascalientes.", descripcion: "Aguascalientes   Sur.", clasificacionId: 2 },
  { ciudad: "Aguascalientes.", descripcion: "Aguascalientes Este.", clasificacionId: 2 },
  { ciudad: "Aguascalientes.", descripcion: "Aguascalientes Norte.", clasificacionId: 3 },
  { ciudad: "Ahome.", descripcion: "Ahome.", clasificacionId: 2 },
  { ciudad: "Arandas.", descripcion: "Arandas", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Azcapotzalgo,Cdmx.", clasificacionId: 2 },
  { ciudad: "Ensenada.", descripcion: "Baja Norte Ensenada.", clasificacionId: 3 },
  { ciudad: "San José del Cabo.", descripcion: "Baja sur  Norte San José del Cabo.", clasificacionId: 2 },
  { ciudad: "Cabo San Lucas.", descripcion: "Baja Sur Cabo San Lucas Centro.", clasificacionId: 1 },
  { ciudad: "Cabo San Lucas.", descripcion: "Baja Sur Cabo San Lucas Este.", clasificacionId: 2 },
  { ciudad: "Cabo San Lucas.", descripcion: "Baja Sur Cabo San Lucas Norte.", clasificacionId: 2 },
  { ciudad: "Cabo San Lucas.", descripcion: "Baja Sur Cabo San Lucas Sur.", clasificacionId: 3 },
  { ciudad: "San José del Cabo.", descripcion: "Baja sur Centro San José del Cabo.", clasificacionId: 1 },
  { ciudad: "Loreto.", descripcion: "Baja Sur Loreto.", clasificacionId: 2 },
  { ciudad: "San José del Cabo.", descripcion: "Baja sur Sur San Jose del Cabo.", clasificacionId: 2 },
  { ciudad: "Boca del rio.", descripcion: "Boca del rio.", clasificacionId: 3 },
  { ciudad: "Campeche.", descripcion: "Campeche.", clasificacionId: 2 },
  { ciudad: "Cancún.", descripcion: "Cancún", clasificacionId: 3 },
  { ciudad: "Cd. Juárez.", descripcion: "CD. JUAREZ.", clasificacionId: 2 },
  { ciudad: "Cd. Madero.", descripcion: "Cd. Madero.", clasificacionId: 2 },
  { ciudad: "Cd. Victoria.", descripcion: "Cd. Victoria", clasificacionId: 2 },
  { ciudad: "Celaya.", descripcion: "Celaya  Centro", clasificacionId: 2 },
  { ciudad: "Celaya.", descripcion: "Celaya Este", clasificacionId: 2 },
  { ciudad: "Celaya.", descripcion: "Celaya Noroeste", clasificacionId: 2 },
  { ciudad: "Celaya.", descripcion: "Celaya Norte", clasificacionId: 2 },
  { ciudad: "Celaya.", descripcion: "Celaya Sur", clasificacionId: 2 },
  { ciudad: "Chetumal.", descripcion: "Chetumal", clasificacionId: 2 },
  { ciudad: "Chihuahua.", descripcion: "Chihuahua Centro.", clasificacionId: 4 },
  { ciudad: "Chihuahua.", descripcion: "Chihuahua Norte.", clasificacionId: 2 },
  { ciudad: "Chihuahua.", descripcion: "Chihuahua Sur.", clasificacionId: 1 },
  { ciudad: "Chilpancingo.", descripcion: "Chilpancingo.", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Coapa Oriente,Cdmx.", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Coapa Poniente,Cdmx.", clasificacionId: 3 },
  { ciudad: "Coatepec.", descripcion: "Coatepec.", clasificacionId: 1 },
  { ciudad: "Coatzacoalcos.", descripcion: "Coatzacoalcos.", clasificacionId: 2 },
  { ciudad: "Colima.", descripcion: "Colima Polígono Este", clasificacionId: 3 },
  { ciudad: "Colima.", descripcion: "colima Polígono Oeste", clasificacionId: 2 },
  { ciudad: "Comitan.", descripcion: "Comitan.", clasificacionId: 2 },
  { ciudad: "Cordova.", descripcion: "Cordova.", clasificacionId: 2 },
  { ciudad: "Cuauhtémoc.", descripcion: "Cuauhtémoc.", clasificacionId: 2 },
  { ciudad: "Culiacán", descripcion: "Culiacán Norte", clasificacionId: 3 },
  { ciudad: "Culiacán", descripcion: "Culiacán Sur", clasificacionId: 2 },
  { ciudad: "Delicias.", descripcion: "Delicias.", clasificacionId: 1 },
  { ciudad: "Durango.", descripcion: "Durango Cap. Oriente.", clasificacionId: 2 },
  { ciudad: "Durango.", descripcion: "Durango Cap. Poniente.", clasificacionId: 3 },
  { ciudad: "Fresnillo.", descripcion: "Fresnillo.", clasificacionId: 2 },
  { ciudad: "Gomez Palacio.", descripcion: "Goméz Palacio.", clasificacionId: 2 },
  { ciudad: "Guadalajara.", descripcion: "Guadalajara Centro", clasificacionId: 4 },
  { ciudad: "Guadalajara.", descripcion: "Guadalajara Este", clasificacionId: 3 },
  { ciudad: "Guadalajara.", descripcion: "Guadalajara Este", clasificacionId: 4 },
  { ciudad: "Guadalajara.", descripcion: "Guadalajara Noreste", clasificacionId: 3 },
  { ciudad: "Guadalajara.", descripcion: "Guadalajara Norte", clasificacionId: 4 },
  { ciudad: "Guadalajara.", descripcion: "Guadalajara sur", clasificacionId: 3 },
  { ciudad: "Guadalupe.", descripcion: "Guadalupe.", clasificacionId: 2 },
  { ciudad: "Guasave.", descripcion: "Guasave.", clasificacionId: 1 },
  { ciudad: "Hermosillo.", descripcion: "Hermosillo Norte", clasificacionId: 2 },
  { ciudad: "Hermosillo.", descripcion: "Hermosillo Sur", clasificacionId: 2 },
  { ciudad: "Heroica Cárdenas", descripcion: "Heroica Cárdenas", clasificacionId: 1 },
  { ciudad: "Huejutla", descripcion: "Huejutla", clasificacionId: 1 },
  { ciudad: "Irapuato.", descripcion: "Irapuato  Sur", clasificacionId: 2 },
  { ciudad: "Irapuato.", descripcion: "Irapuato Este", clasificacionId: 2 },
  { ciudad: "Irapuato.", descripcion: "Irapuato Noroeste", clasificacionId: 2 },
  { ciudad: "Irapuato.", descripcion: "Irapuato Norte", clasificacionId: 2 },
  { ciudad: "Irapuato.", descripcion: "Irapuato Sureste", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Iztapalapa,Cdmx.", clasificacionId: 2 },
  { ciudad: "Jeréz.", descripcion: "Jeréz.", clasificacionId: 1 },
  { ciudad: "Juchitán", descripcion: "Juchitán", clasificacionId: 2 },
  { ciudad: "León.", descripcion: "Leon Polígono  Centro Sur", clasificacionId: 2 },
  { ciudad: "León.", descripcion: "Leon Polígono  Oeste", clasificacionId: 2 },
  { ciudad: "León.", descripcion: "Leon Polígono Bronce Sureste", clasificacionId: 1 },
  { ciudad: "León.", descripcion: "Leon Polígono Centro Norte", clasificacionId: 3 },
  { ciudad: "León.", descripcion: "Leon Polígono Este", clasificacionId: 2 },
  { ciudad: "León.", descripcion: "Leon Polígono Norte", clasificacionId: 4 },
  { ciudad: "León.", descripcion: "Leon Polígono Sur", clasificacionId: 3 },
  { ciudad: "León.", descripcion: "Leon Polígono Suroeste", clasificacionId: 1 },
  { ciudad: "Loreto Zac.", descripcion: "Loreto Zac.", clasificacionId: 1 },
  { ciudad: "Matamoros", descripcion: "Matamoros", clasificacionId: 1 },
  { ciudad: "Mazatlán.", descripcion: "Mazatlán.", clasificacionId: 3 },
  { ciudad: "Merida Norte.", descripcion: "Merida Norte.", clasificacionId: 3 },
  { ciudad: "Merida Sur.", descripcion: "Merida Sur.", clasificacionId: 2 },
  { ciudad: "Metepec ", descripcion: "Metepec ", clasificacionId: 4 },
  { ciudad: "Minatitlan.", descripcion: "Minatitlan.", clasificacionId: 1 },
  { ciudad: "Monclova", descripcion: "Monclova", clasificacionId: 2 },
  { ciudad: "Morelia.", descripcion: "Morelia Centro Oeste", clasificacionId: 3 },
  { ciudad: "Morelia.", descripcion: "Morelia Este", clasificacionId: 4 },
  { ciudad: "Morelia.", descripcion: "Morelia Noreste", clasificacionId: 2 },
  { ciudad: "Morelia.", descripcion: "Morelia Noroeste", clasificacionId: 3 },
  { ciudad: "Morelia.", descripcion: "Morelia Sur   ", clasificacionId: 2 },
  { ciudad: "Morelia.", descripcion: "Morelia Sureste", clasificacionId: 3 },
  { ciudad: "Cuautla.", descripcion: "Morelos Cuautla.", clasificacionId: 1 },
  { ciudad: "Cuernavaca.", descripcion: "Morelos Norte.", clasificacionId: 3 },
  { ciudad: "Cuernavaca.", descripcion: "Morelos Sur.", clasificacionId: 2 },
  { ciudad: "Allende.", descripcion: "N.L. Allende.", clasificacionId: 2 },
  { ciudad: "Apodaca.", descripcion: "N.L. Apodaca.", clasificacionId: 3 },
  { ciudad: "Monterrey.", descripcion: "N.L. Carretera Nac.", clasificacionId: 3 },
  { ciudad: "Monterrey.", descripcion: "N.L. Country.", clasificacionId: 3 },
  { ciudad: "Monterrey.", descripcion: "N.L. Cumbres.", clasificacionId: 3 },
  { ciudad: "San Nicolás.", descripcion: "N.L. San Nicolás.", clasificacionId: 2 },
  { ciudad: "San Pedro.", descripcion: "N.L. San Pedro.", clasificacionId: 4 },
  { ciudad: "Monterrey.", descripcion: "N.L. Santa Catarina.", clasificacionId: 2 },
  { ciudad: "Monterrey.", descripcion: "N.L.Monterrey.", clasificacionId: 4 },
  { ciudad: "CDMX.", descripcion: "Narvarte Oriente,Cdmx.", clasificacionId: 3 },
  { ciudad: "CDMX.", descripcion: "Narvarte Poniente,Cdmx.", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Naucalpan Poniente,Cdmx.", clasificacionId: 2 },
  { ciudad: "Navojoa", descripcion: "Navojoa", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Nucalpan Oriente,Cdmx.", clasificacionId: 2 },
  { ciudad: "Oaxaca.", descripcion: "Oaxaca Cap. Norte", clasificacionId: 3 },
  { ciudad: "Oaxaca.", descripcion: "Oaxaca Cap. Sur.", clasificacionId: 2 },
  { ciudad: "Obregón", descripcion: "Obregón", clasificacionId: 1 },
  { ciudad: "Obregón ", descripcion: "Obregón ", clasificacionId: 2 },
  { ciudad: "Orizaba.", descripcion: "Orizaba Norte.", clasificacionId: 2 },
  { ciudad: "Orizaba.", descripcion: "Orizaba Sur.", clasificacionId: 3 },
  { ciudad: "Pachuca.", descripcion: "Pachuca Este", clasificacionId: 3 },
  { ciudad: "Pachuca.", descripcion: "Pachuca Norte", clasificacionId: 2 },
  { ciudad: "Pachuca.", descripcion: "Pachuca Oeste", clasificacionId: 2 },
  { ciudad: "Pachuca.", descripcion: "Pachuca sur", clasificacionId: 2 },
  { ciudad: "Playa del Carmen.", descripcion: "Playa del Carmen.", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Polanco,Cdmx.", clasificacionId: 4 },
  { ciudad: "Poza Rica.", descripcion: "Poza Rica.", clasificacionId: 2 },
  { ciudad: "Puebla.", descripcion: "Puebla Centro  ", clasificacionId: 3 },
  { ciudad: "Puebla.", descripcion: "Puebla Centroeste", clasificacionId: 3 },
  { ciudad: "Puebla.", descripcion: "Puebla Este", clasificacionId: 2 },
  { ciudad: "Puebla.", descripcion: "Puebla Norte", clasificacionId: 3 },
  { ciudad: "Puebla.", descripcion: "Puebla Sur", clasificacionId: 4 },
  { ciudad: "Puebla.", descripcion: "Puebla Sureste", clasificacionId: 2 },
  { ciudad: "Querétaro.", descripcion: "Querétaro Centro", clasificacionId: 4 },
  { ciudad: "Querétaro.", descripcion: "Querétaro Centro/Norte", clasificacionId: 2 },
  { ciudad: "Querétaro.", descripcion: "Querétaro Diamante Este", clasificacionId: 4 },
  { ciudad: "Querétaro.", descripcion: "Querétaro Noroeste", clasificacionId: 4 },
  { ciudad: "Querétaro.", descripcion: "Querétaro Norte", clasificacionId: 2 },
  { ciudad: "Querétaro.", descripcion: "Querétaro Sur", clasificacionId: 3 },
  { ciudad: "Reynosa.", descripcion: "Reynosa", clasificacionId: 1 },
  { ciudad: "Rio Verde", descripcion: "Rio Verde", clasificacionId: 1 },
  { ciudad: "CDMX.", descripcion: "Roma,Cdmx.", clasificacionId: 3 },
  { ciudad: "Salina Cruz.", descripcion: "Salina Cruz.", clasificacionId: 2 },
  { ciudad: "Saltillo.", descripcion: "Saltillo Norte.", clasificacionId: 3 },
  { ciudad: "Saltillo.", descripcion: "Saltillo Sur.", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "San Angel Cdmx.", clasificacionId: 3 },
  { ciudad: "San Cristobal.", descripcion: "San Cristobal Norte.", clasificacionId: 2 },
  { ciudad: "Tapachula.", descripcion: "San cristobal Sur.", clasificacionId: 2 },
  { ciudad: "San Juan de los Lagos.", descripcion: "San Juan de los Lagos ", clasificacionId: 2 },
  { ciudad: "San Juan del Rio.", descripcion: "San Juan del Rio", clasificacionId: 2 },
  { ciudad: "San Luis Potosí", descripcion: "San Luis Potosí", clasificacionId: 3 },
  { ciudad: "San Luis Potosí", descripcion: "San Luis Potosí", clasificacionId: 3 },
  { ciudad: "San Luis Potosí", descripcion: "San Luis Potosí", clasificacionId: 3 },
  { ciudad: "San Luis Potosí", descripcion: "San Luis Potosí", clasificacionId: 2 },
  { ciudad: "San Luis Potosí", descripcion: "San Luis Potosí", clasificacionId: 2 },
  { ciudad: "San Luis Potosí", descripcion: "San Luis Potosí", clasificacionId: 2 },
  { ciudad: "San Luis Potosi", descripcion: "San Luis Potosí", clasificacionId: 4 },
  { ciudad: "San Miguel Allende.", descripcion: "San Miguel Allende Centro", clasificacionId: 2 },
  { ciudad: "San Miguel Allende.", descripcion: "San Miguel Allende Noreste", clasificacionId: 2 },
  { ciudad: "San Miguel Allende.", descripcion: "San Miguel Allende Norte", clasificacionId: 2 },
  { ciudad: "San Miguel Allende.", descripcion: "San Miguel Allende Sur", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Santa Fé Norte.", clasificacionId: 4 },
  { ciudad: "CDMX.", descripcion: "Santa Fé Sur.", clasificacionId: 4 },
  { ciudad: "Tampico.", descripcion: "Tampico.", clasificacionId: 2 },
  { ciudad: "Comitan.", descripcion: "Tapachula", clasificacionId: 2 },
  { ciudad: "Tepatitlan.", descripcion: "Tepatitlan", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Tepeyac,Cdmx.", clasificacionId: 2 },
  { ciudad: "Tepic.", descripcion: "Tepic Este", clasificacionId: 1 },
  { ciudad: "Tepic.", descripcion: "Tepic Norte", clasificacionId: 2 },
  { ciudad: "Tepic.", descripcion: "Tepic Oeste", clasificacionId: 2 },
  { ciudad: "Tepic.", descripcion: "Tepic Sur", clasificacionId: 2 },
  { ciudad: "Tepic.", descripcion: "Tepic Sureste", clasificacionId: 2 },
  { ciudad: "Edo. Mex", descripcion: "Tequixquiac, Edo.Méx.", clasificacionId: 2 },
  { ciudad: "Tezontepec.", descripcion: "Tezontepec", clasificacionId: 1 },
  { ciudad: "Tlaxiaco.", descripcion: "Tlaxiaco", clasificacionId: 2 },
  { ciudad: "Torreón.", descripcion: "Torreón Oriente.", clasificacionId: 3 },
  { ciudad: "Torreón.", descripcion: "Torreón Poniente.", clasificacionId: 2 },
  { ciudad: "Tula.", descripcion: "Tula ", clasificacionId: 2 },
  { ciudad: "Tuxpan.", descripcion: "Tuxpan Guerrero.", clasificacionId: 1 },
  { ciudad: "Tuxtla Gutierrez.", descripcion: "Tuxtla Norte.", clasificacionId: 2 },
  { ciudad: "Tuxtla Gutierrez.", descripcion: "Tuxtla Sur.", clasificacionId: 2 },
  { ciudad: "Tuxtla Ver.", descripcion: "Tuxtla Ver.", clasificacionId: 1 },
  { ciudad: "CDMX.", descripcion: "Universidad,Cdmx.", clasificacionId: 3 },
  { ciudad: "Vallarta.", descripcion: "Vallarta Centro", clasificacionId: 2 },
  { ciudad: "Vallarta.", descripcion: "Vallarta Este", clasificacionId: 2 },
  { ciudad: "Vallarta.", descripcion: "Vallarta Norte ", clasificacionId: 2 },
  { ciudad: "CDMX.", descripcion: "Valle de Bravo, Oriente.", clasificacionId: 3 },
  { ciudad: "CDMX.", descripcion: "Valle de Bravo, Poniente.", clasificacionId: 3 },
  { ciudad: "Veracruz Pto.", descripcion: "Veracruz Pto.", clasificacionId: 2 },
  { ciudad: "Villahermosa.", descripcion: "Villahermosa.", clasificacionId: 3 },
  { ciudad: "Xalapa.", descripcion: "Xalapa Norte.", clasificacionId: 2 },
  { ciudad: "Xalapa.", descripcion: "Xalapa Sur.", clasificacionId: 3 },
  { ciudad: "Zacatecas.", descripcion: "Zacatecas", clasificacionId: 2 },
  { ciudad: "Zamora.", descripcion: "Zamora Norte", clasificacionId: 2 },
  { ciudad: "Zamora.", descripcion: "Zamora Sur", clasificacionId: 2 },
  { ciudad: "Zihuatanejo.", descripcion: "Zihuatanejo", clasificacionId: 1 }
];