export interface ProgramaEspecialImpulso{
    descripcion: string,
    valor: string
}

export const LISTA_PROGRAMA_ESPECIAL_IMPULSO: ProgramaEspecialImpulso[] = [
    { descripcion: "Programa de BICICLETAS DEMO" , valor: "Consiste en adquirir un mínimo de 2 y un máximo de 8 bicicletas elegibles para el programa, en cualquier momento durante la temporada. Estas bicicletas serán utilizadas como demostradores para promover el uso de nuestras diversas líneas de bicicletas. Beneficios: Línea de crédito adicional** a la línea actual (limitada a un máximo del 50% del monto de la línea actual). Bicicletas que no son Carry Over y son nuevas líneas, 40% descuento sobre precio al público. Plazo especial de pago de 90, 120, 150 o 180 días. Para las bicicletas Carry Over solo aplica un 5% sobre el precio de cada nivel de distribución. *Excepto bicicletas eléctricas, cuentan con su propio programa."},
    { descripcion: "Programa de BICICLETAS Electricas" , valor: "Consiste en realizar una compra de al menos 1 y como máximo 6 bicicletas eRIDE o EBikes en cualquier momento durante la temporada, como parte del programa de bicicletas Demo y para fomentar el uso de bicicletas eléctricas. Beneficios: Línea de crédito adicional** a la línea actual (limitada a un máximo del 50% del monto de la línea actual). Bicicletas que no son Carry Over y son nuevas líneas, 40% descuento sobre precio al Público Plazo especial de pago de 10 mensualidades. Las bicicletas Carry Over solo aplica un 5% sobre el precio de cada nivel de distribución."},
    { descripcion: "SYNCROS Programa Impulso" , valor: "Consiste en impulsar la marca Syncros desde inicio de temporada a través de su exhibición y disponibilidad  en los puntos de venta de los distribuidores, excepto ruedas (ver programa Ruedas Syncros). Beneficios: Línea de crédito adicional** a la línea actual (limitada a un máximo del 50% del monto de la línea actual). Plazo especial de pago de 60, 90 o 120 días."},
    { descripcion: "SYNCROS Programa Especial Ruedas" , valor: "Consiste en realizar una compra inicial de al menos 2 y como máximo 4 Ruedas Syncros en cualquier momento durante la temporada, para ser utilizadas como demostradores y promover su uso. Beneficios: Línea de crédito adicional** a la línea actual (limitada a un máximo del 50% del monto de la línea actual). Descuento del 43% sobre el precio mínimo sugerido al público de la compra. o el precio de descuento al distribuidor, lo que sea más bajo. Plazo especial de pago de 90, 120, 150 o 180 días."},
    { descripcion: "APPAREL SCOTT" , valor: "Consiste en impulsar todas las líneas de apparel (ropa, zapatos, cascos, guantes, lentes, protecciones, bolsas y mochilas) desde inicio de temporada a través de su exhibición y disponibilidad  en los puntos de venta. Beneficios: Línea de crédito adicional** a la línea actual, para la compra de Apparel en todas sus líneas (ropa, zapatos, cascos, guantes, lentes, protecciones, bolsas y mochilas), por un importe igual al 50% de la compra mínima de Apparel estipulada en cada nivel de distribuidor. Plazo especial de pago de 60, 90, o 120 días."},
    { descripcion: "PROGRAMA IMPULSO VITTORIA" , valor: "Consiste en impulsar la marca Vittoria para la compra de llantas y productos desde inicio de temporada a través de su exhibición y disponibilidad en los puntos de venta. Beneficios: Línea de crédito adicional** a la línea actual  por un importe maximo de $90,000 , siempre y cuando sea superior a $35,000.00 (IVA incluido). Plazo especial de pago de 60, 90 o 120 días"},
    { descripcion: "PROGRAMA COMPRA DE EMPLEADOS" , valor: "Con la finalidad de apoyar a la fuerza de venta para adquirir equipo de la marca SCOTT, ofrecemos el programa de compra de bicicleta y equipo para empleados el cual consiste en: Para las bicicletas Carry Over solo aplica un 5% sobre el precio de cada nivel de distribución. Para las bicicletas que no son Carry Over y son nuevas líneas, 43% descuento sobre precio al público de hasta una bicicleta por temporada, un casco, dos pares de ruedas y un par de zapatos."},
]
  